//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class formasfarmaceuticas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public formasfarmaceuticas()
        {
            this.medicamentos = new HashSet<medicamentos>();
        }
    
        public int idformafarmaceutica { get; set; }
        public string nombre { get; set; }
        public Nullable<int> habilitado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medicamentos> medicamentos { get; set; }
    }
}
