//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicamentos
    {
        public int idmedicamento { get; set; }
        public string nombre { get; set; }
        public string concentracion { get; set; }
        public Nullable<int> idformafarmaceutica { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> stock { get; set; }
        public string presentacion { get; set; }
        public Nullable<int> bhabilitado { get; set; }
    
        public virtual formasfarmaceuticas formasfarmaceuticas { get; set; }
    }
}
