//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int idusuario { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
        public Nullable<int> idperfil { get; set; }
        public Nullable<int> estatus { get; set; }
    }
}
